version: '3.8'

services:
  webserver:
    build: ./img/webserver
    image: webserver
    container_name: webserver
    ports:
      - '${WEBSERVER_HTTP_PORT:?}:80'
      - '${WEBSERVER_HTTPS_PORT:?}:443'
    environment:
      XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST:?}
      XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT:?}
    volumes:
      - '${WEBSERVER_DOCUMENT_ROOT:?}:/var/www/html'
      - '${WEBSERVER_PHP_INI:?}:/usr/local/etc/php/php.ini'
      - '${WEBSERVER_VHOST_DIR:?}:/etc/apache2/sites-enabled'
      - '${WEBSERVER_VHOST_DIR:?}:/etc/apache2/sites-available'
      - '${WEBSERVER_LOG_DIR:?}:/var/log/apache2'
    networks:
      - appnet
    restart: always

  mysql:
    build: ./img/mysql
    image: mysql
    container_name: mysql
    ports:
      - '${MYSQL_PORT:?}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - '${MYSQL_VOL_DIR:?}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR:?}:/var/log/mysql'
    networks:
      - appnet
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    restart: always

  postgres:
    build: ./img/postgres
    image: postgres
    container_name: postgres
    ports:
      - '${POSTGRES_PORT:?}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    volumes:
      - '${POSTGRES_VOL_DIR:?}:/var/lib/postgresql/data'
      - '${POSTGRES_LOG_DIR:?}:/logs:z'
    networks:
      - appnet
    # Make Postgres log to a file.
    command: /bin/bash -c "mkdir -p /logs && chmod -R 777 /logs && postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs"
    restart: always

  phpmyadmin:
    build: ./img/phpmyadmin
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - '${PMA_PORT:?}:80'
    environment:
      PMA_HOST: mysql
      PMA_PMADB: phpmyadmin
      PMA_PORT: ${MYSQL_PORT:?}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:?}
      MEMORY_LIMIT: ${PMA_MEMORY_LIMIT:?}
    volumes: 
      - /sessions
    networks:
      - appnet
    depends_on:
      - mysql
    restart: always

  rabbitmq:
    build: ./img/rabbitmq
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - '${RABBITMQ_PORT_1:?}:5672'
      - '${RABBITMQ_PORT_2:?}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:?}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:?}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:?}
    volumes:
      - '${RABBITMQ_VOL_DIR:?}:/var/lib/rabbitmq'
      - '${RABBITMQ_LOG_DIR:?}:/var/log/rabbitmq'
    networks:
      - appnet
    restart: always

  redis:
    build: ./img/redis
    image: redis
    container_name: redis
    ports:
      - '${REDIS_PORT:?}:6379'
    volumes:
      - '${REDIS_VOL_DIR:?}:/data'
    networks:
      - appnet
    restart: always

  mailhog:
    build: ./img/mailhog
    image: mailhog
    container_name: mailhog
    ports:
      - '${MAILHOG_PORT1:?}:1025'
      - '${MAILHOG_PORT2:?}:8025'
    networks:
      - appnet
    restart: always

networks:
  appnet:
    name: appnet
    driver: bridge
