version: '3'

services:
  webserver:
    build:
      context: img/webserver
    restart: always
    ports:
      - 80:80
    links:
      - mysql
    volumes:
      - ./www:/var/www/html
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/vhosts:/etc/apache2/sites-enabled
      - ./log/apache2:/var/log/apache2
    tty: true
  mysql:
    build:
      context: img/mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"

  phpmyadmin:
    build:
      context: img/phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    volumes:
      - /sessions
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  mailhog:
    build:
      context: img/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
