version: '3'

services:
  webserver:
    build:
      context: img/webserver
    restart: always
    ports:
      - 80:80
    links:
      - mysql
      - redis
      - postgres
      - rabbitmq
    volumes:
      - ./www:/var/www/html
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/vhost:/etc/apache2/sites-enabled
      - ./cfg/vhost:/etc/apache2/sites-available
      - ./log/apache2:/var/log/apache2

  mysql:
    build:
      context: img/mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"

  postgres:
    build:
      context: img/postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  phpmyadmin:
    build:
      context: img/phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    volumes:
      - /sessions
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  rabbitmq:
    build:
      context: img/rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_DEFAULT_VHOST: "/"

  redis:
    build:
      context: img/redis
    restart: always
    ports:
      - 6379:6379

  mailhog:
    build:
      context: img/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  pgdata:
    driver: local
